version: v1

labels:
  - label: "javascript-changes"
    sync: true
    matcher:
      files:
        any:
          - "*.js"
          - "*.jsx"

  - label: "css-changes"
    sync: true
    matcher:
      files:
        any:
          - "*.css"

  - label: "feature"
    sync: true
    matcher:
      body: "/\\[x\\] Feature/"

  - label: "bug fix"
    sync: true
    matcher:
      body: "/\\[x\\] Bug Fix/"

  - label: "documentation"
    sync: true
    matcher:
      body: "/\\[x\\] Documentation/"

  - label: "other"
    sync: true
    matcher:
      body: "/\\[x\\] Other/"
