name: GitHub Script Example

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            // Add a label to the pull request
            await github.rest.pulls.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: ['your-label-name']
            });
