name: Label Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Label Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const description = github.context.payload.pull_request.body.toLowerCase();

            if (description.includes('bug')) {
              github.issues.addLabels({
                issue_number: github.context.payload.pull_request.number,
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                labels: ['bug']
              });
            }

            // You can add more conditions and labels as needed

        env:
          GITHUB_TOKEN: ${{ github.token }}
