name: Label Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set PR Label
        run: |
          PR_TYPE=$(grep -oP '(?<=\[ \] \b).+' ${{ github.event.before }}..${{ github.sha }} -- PULL_REQUEST_TEMPLATE.md)
          echo "PR_TYPE=$PR_TYPE"
          if [ -n "$PR_TYPE" ]; then
            # Assign labels based on the selected type
            case $PR_TYPE in
              "Bug fix")
                echo "Setting label: bug-fix"
                gh pr edit ${{ github.event.number }} --add-label bug-fix
                ;;
              "New feature")
                echo "Setting label: new-feature"
                gh pr edit ${{ github.event.number }} --add-label new-feature
                ;;
              "Enhancement")
                echo "Setting label: enhancement"
                gh pr edit ${{ github.event.number }} --add-label enhancement
                ;;
              "Documentation")
                echo "Setting label: documentation"
                gh pr edit ${{ github.event.number }} --add-label documentation
                ;;
              *)
                echo "Unknown type: $PR_TYPE"
                ;;
            esac
          else
            echo "No type selected in the pull request template."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
