name: Auto Label on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Auto Label on Pull Request
        run: node .github/auto-label.js
