name: PR Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run labeler
        run: npx labeler --config .github/labeler-config.yml
